version: '3'
services:

  latest:
    build: .
    ports:
     - "8020:80"

  blue:
    image: tonanuvem/fiap_page:blue
    ports:
     - "8021:80"
     
  green:
    image: tonanuvem/fiap_page:green
    ports:
     - "8022:80"
     
  slack:
    image: tonanuvem/fiap_page:slack
    ports:
     - "8023:80"
     
  teams:
    image: tonanuvem/fiap_page:teams
    ports:
     - "8024:80"
